import{a as d,S as v,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="53371972-407ae4137ffe2ff2cf6f525d2";d.defaults.baseURL="https://pixabay.com/api/";const f=15;async function M(r,t){const s={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:t};return(await d.get("/",{params:s})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function P(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:n,comments:w,downloads:S})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${i}">
                <img class="gallery-image" src="${s}" alt="${e}" />
            </a>
            <div class="info">
                <p><b>Likes</b> ${o}</p>
                <p><b>Views</b> ${n}</p>
                <p><b>Comments</b> ${w}</p>
                <p><b>Downloads</b> ${S}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t),q.refresh()}function g(){p.innerHTML=""}function R(){m.classList.remove("is-hidden")}function B(){m.classList.add("is-hidden")}function $(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const y=document.querySelector(".form"),H=document.querySelector(".load-more");let b="",c=1,u=0;y.addEventListener("submit",O);H.addEventListener("click",x);async function O(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){a.warning({title:"Увага",message:"Введи, будь ласка, пошуковий запит 🙂",position:"topRight"});return}b=t,c=1,u=0,g(),l(),await L({isNewSearch:!0}),y.reset()}async function x(){await L({isNewSearch:!1})}async function L({isNewSearch:r}){R(),l();try{const t=await M(b,c),{hits:s,totalHits:i}=t;if(r){if(!s.length){g(),a.info({title:"Нічого не знайдено",message:"Спробуй інший запит 😉",position:"topRight"});return}u=i}if(!s.length){l(),a.info({title:"Упс",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}P(s),c>1&&N();const e=Math.ceil(u/f);c<e?$():(l(),a.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),c+=1}catch{a.error({title:"Помилка",message:"Сталася помилка під час завантаження. Спробуй ще раз пізніше.",position:"topRight"})}finally{B()}}function N(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
